import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { getOrganizerAnalytics } from "../api/analyticsApi";
import { publishEvent } from "../api/eventApi";
import { checkInTicket } from "../api/ticketApi";

function OrganizerDashboard() {
  const [data, setData] = useState(null); const [message, setMessage] = useState(""); const [ticketId, setTicketId] = useState(""); const [checkinMessage, setCheckinMessage] = useState("");
  const loadDashboard = () => getOrganizerAnalytics().then((response) => setData(response.data)).catch(() => setMessage("Please log in with an organizer account."));
  useEffect(() => { loadDashboard(); }, []);
  const publish = async (eventId) => { try { await publishEvent(eventId); loadDashboard(); } catch (error) { setMessage(error.response?.data?.error?.message || "The event could not be published."); } };
  const checkIn = async (event) => { event.preventDefault(); try { await checkInTicket(ticketId); setCheckinMessage("Ticket checked in successfully."); setTicketId(""); } catch (error) { setCheckinMessage(error.response?.data?.error?.message || "Could not check in this ticket."); } };
  if (message) return <div className="p-12 text-center">{message}</div>; if (!data) return <div className="p-12 text-center">Loading dashboard…</div>;
  const stats = [["Total Events", data.totalEvents], ["Tickets Sold", data.totals.totalTicketsSold], ["Revenue", `₹${data.totals.totalRevenue.toLocaleString("en-IN")}`]];
  return <div className="min-h-screen bg-slate-50"><section className="border-b bg-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-10"><div><p className="text-sm font-semibold uppercase text-slate-500">Organizer</p><h1 className="mt-2 text-4xl font-bold">Organizer Dashboard</h1></div><Link to="/create-event" className="rounded-lg bg-slate-900 px-5 py-3 text-white">Create Event</Link></div></section><section className="mx-auto max-w-7xl px-6 py-10"><div className="grid gap-6 md:grid-cols-3">{stats.map(([title, value]) => <div key={title} className="rounded-xl border bg-white p-6 shadow-sm"><p className="text-sm text-slate-500">{title}</p><p className="mt-2 text-3xl font-bold">{value}</p></div>)}</div><form onSubmit={checkIn} className="mt-8 flex max-w-xl gap-2 rounded-xl border bg-white p-5"><input required value={ticketId} onChange={(event) => setTicketId(event.target.value)} placeholder="Ticket ID for check-in" className="min-w-0 flex-1 rounded border p-3"/><button className="rounded bg-slate-900 px-4 text-white">Check in</button>{checkinMessage && <p className="self-center text-sm">{checkinMessage}</p>}</form><div className="mt-10 overflow-hidden rounded-xl border bg-white"><table className="w-full text-left"><thead className="bg-slate-50"><tr><th className="p-4">Event</th><th className="p-4">Date</th><th className="p-4">Tickets Sold</th><th className="p-4">Revenue</th><th className="p-4">Status</th><th className="p-4">Action</th></tr></thead><tbody>{data.events.map((event) => <tr key={event.event_id} className="border-t"><td className="p-4 font-medium">{event.title}</td><td className="p-4">{new Date(event.event_date).toLocaleDateString()}</td><td className="p-4">{event.tickets_sold}</td><td className="p-4">₹{Number(event.revenue).toLocaleString("en-IN")}</td><td className="p-4 capitalize">{event.status}</td><td className="p-4">{event.status === "draft" && <button onClick={() => publish(event.event_id)} className="underline">Publish</button>}</td></tr>)}</tbody></table></div></section></div>;
}
export default OrganizerDashboard;
